[[definitions]]
= Definitions

****
Catalogue::
A catalogue is a structured document of items (e.g., goods and services) description that is available in a format so that it can be processed electronically.

Pre-award catalogue request::
A pre-award catalogue request is a catalogue of requirements on products (goods or services) intended to be bought by a Contracting Authority. +
_SOURCE: CWA 17028-402:2016, definition 3.3_

Pre-award catalogue::
A pre-award catalogue is a catalogue used by an economic operator to provide the information on the offered products as an answer to a call for tenders and the corresponding pre-award catalogue request. +
_SOURCE: CWA 17028-402:2016, definition 3.2_

Post-award catalogue::
A post-award catalogue is a catalogue used by an economic operator to provide the information in the post-award phase, i.e., to provide the information necessary for a placing an order for requested items with an economic operator. +
A post-award catalogue might be based on a pre-award catalogue as well as based on a framework agreement or an agreement from a tender.
****