= Attachments

Attachments can be sent on line level in the pre award catalogue request, to add further item specifications. In the request no binary attachments are allowed, only providing external uri to the document, and also the possibility to add information on hash-value.

In the pre-award catalogue additional specifications or product images can be sent. In both the request and the catalogue, the element used is `cac:ItemSpecificationDocumentReference`

====
IMPORTANT: It is strongly recommended to use external references in the form of URI’s for attachments.
====


.Example of using external reference in the pre-award catalogue
[source, xml, indent=0]
----
<cac:Item>
  ...
  <cac:ItemSpecificationDocumentReference>
    <cbc:ID>LK8788</cbc:ID>
    <cbc:DocumentDescription>Product image</cbc:DocumentDescription>
    <cac:Attachment>
      <cac:ExternalReference>
        <cbc:URI>http://img.trioving.net/Låskasser/LK8788_PRD_FPM_000.JPG</cbc:URI>
      </cac:ExternalReference>
    </cac:Attachment>
  </cac:ItemSpecificationDocumentReference>
  ...
</cac:Item>

----

If binary objects are attached to the Pre-Award Catalogue, the valid values for mimetype can be found in codelist.

.Example of using attached binary objects
[source, xml, indent=0]
----
include::../../{snippet-dir}/Catalogue-guide.xml[tags=ItemSpecificationDocumentReference2]
----
