
= Environment, Social and Innovative requirements

Public actors may have special green, social or innovative requirements to the works, supplies or services they intend to purchase, and they might ask for labels, test reports, certificates or other means of proof for these requirements.

IMPORTANT: Contracting authorities requiring a specific label shall accept all labels that confirm that the works, supplies or services meet *equivalent* label requirements.

These requirements are sent in the element 'cac:Certificate' in the pre award catalogue request, and the economic operator sends their answer and attachments (if any), in the `cac:Certificate`-element in the pre award catalogue.

The 'cac:Certificate' contains detailed information on the requirement(s), if the requirement is absolute or an award criteria. In addition, the type of evidence (means of proof) that can be used is stated as well.



.Example showing a requirement to fulfill the EU GPP energy criteria for computers, and stating that a Type 1 (or equivalent) certificate can be used as means of proof.
[source, xml, indent=0]
----
include::../../{snippet-dir}/CatalogueRequest-guide.xml[tags=Certificate]
----
<1> Main level requirement
<2> Specific requirement
<3> The requirement is absolute.
<4> A Type 1 certificate is asked for as the means of proof level
<5> Green requirement
<6> Reference to the specification of the suggested means of proof.


.Example showing a response to this requirement in the pre-award catalogue, providing another type of proof then what is mentioned in the request.
[source, xml, indent=0]
----
include::../../{snippet-dir}/Catalogue-guide.xml[tags=Certificate]
----
<1> The identifier must be the same as what was sent in the request.
<2> References to the general requirement as sent in the request
<3> Reference to the specific requirement as sent in the request
<4> Means of proof level provided
<5> Specific means of proof details
<6> Description of the means of proof
<7> Link to the database for registration.


== Life cycle analysis (LCA)

Below you can find two examples on how to state requirements on LCA

[source, xml, indent=0]
----
include::../../{snippet-dir}/CatalogueRequest-guide.xml[tags=LCA]
----
