
= Logistics Information

The Pre-Award Catalogue includes elements to support the need for logistics information which is a requirement in many industries. These elements are not mandatory, but trading partners can agree upon the use in the commercial agreements.

The Logistics elements can be used to specify different pack levels for the same article. This shall be done as follows:

* Each pack level is regarded as a unique product and shall be sent as a separate Catalogue line and identified with a unique ID such as GTIN.
* Information about pack level is done in the element PackLevelCode on line level. The Pack level codes are based on the Edifact/Eancom-standard and the following codes are available (codes in brackets are used in some business sectors in Norway):
** DU = Dispatch Unit (T-Pak)
** HN = Handling Unit (level between TU and DU). Not commonly used.
** TU = Traded Unit (D-Pak or L-Pak)
** CU = Consumer Unit (F-Pak)
* It shall be stated if the pack level is orderable.
* The relation between pack levels shall be specified, e.g. that a Dispatch unit contains Traded units.

WARNING: When component related items are used, all the items in the Pre-Award Catalogue shall specify the Sellers item identifier

Below is an example of Logistics information in a Pre-Award Catalogue message.

.Catalogue line for Dispatch unit, highest pack level.
[source, xml, indent=0]
----
<cac:CatalogueLine>
		<cbc:ID>1</cbc:ID>
		<cbc:OrderableIndicator>false</cbc:OrderableIndicator>
		<cbc:PackLevelCode>DU</cbc:PackLevelCode>
		<cac:ComponentRelatedItem>
			<cbc:ID>222222</cbc:ID> <!--1-->
			<cbc:Quantity unitCode="EA">12</cbc:Quantity> <!--2-->
		</cac:ComponentRelatedItem>
		<cac:Item>
			<cbc:Description>Soft drink, pallet</cbc:Description>
			<cbc:PackQuantity unitCode="EA">1</cbc:PackQuantity>
			<cbc:Name languageID="en">Soft drink</cbc:Name>
			<cac:SellersItemIdentification>
				<cbc:ID>111111</cbc:ID>
			</cac:SellersItemIdentification>
		</cac:Item>
	</cac:CatalogueLine>
----
<1>  References the sellers item identification for the component line
<2>  Quantity of that component (each dispatch unit contains 12 traded units)


.Catalogue line for Traded unit.
[source, xml, indent=0]
----
<cac:CatalogueLine>
    <cbc:ID>2</cbc:ID>
    <cbc:OrderableIndicator>true</cbc:OrderableIndicator>
    <cbc:OrderableUnit>5</cbc:OrderableUnit>
    <cbc:PackLevelCode>TU</cbc:PackLevelCode>
    <cac:ComponentRelatedItem>
        <cbc:ID>333333</cbc:ID> <!--1-->
        <cbc:Quantity unitCode="EA">6</cbc:Quantity> <!--2-->
    </cac:ComponentRelatedItem>
    <cac:Item>
        <cbc:Description>Soft drink, trading unit</cbc:Description>
        <cbc:PackQuantity unitCode="EA">1</cbc:PackQuantity>
        <cbc:Name languageID="en">Soft drink</cbc:Name>
        <cac:SellersItemIdentification>
            <cbc:ID>222222</cbc:ID>
        </cac:SellersItemIdentification>
    </cac:Item>
</cac:CatalogueLine>
----
<1>  References the sellers item identification for the component line
<2>  Quantity of that component (each traded unit contains 6 consumer units)

.Catalogue line for Consumer unit, lowest pack level.
[source, xml, indent=0]
----
<cac:CatalogueLine>
    <cbc:ID>3</cbc:ID>
    <cbc:OrderableIndicator>false</cbc:OrderableIndicator>
    <cbc:PackLevelCode>CU</cbc:PackLevelCode>
    <cac:Item>
        <cbc:Description>Soft drink 4-pack</cbc:Description>
        <cbc:PackQuantity unitCode="EA">1</cbc:PackQuantity>
        <cbc:Name languageID="en">Soft drink</cbc:Name>
        <cac:SellersItemIdentification>
            <cbc:ID>333333</cbc:ID>
        </cac:SellersItemIdentification>
    </cac:Item>
</cac:CatalogueLine>
----
