= Requested Item Properties

Requested item properties are used in the pre-award catalogue request transaction to request specific properties of an item, like a specific colour of an item, and is sent in the UBL element `cac:AdditionalItemProperty`. This element can contain information on requested property name, quantity, range, classification and request relevance, i.e if the property request is optional, forbidden or used for evaluation purposes. If the relevance code is not set this means that information on that property shall be included in the corresponding pre-award catalogue, i.e it is mandatory. If the code is F (forbidden) this cannot be a property of the item, and hence its value shall not be sent in the catalogue.

IMPORTANT: The requested item property identifier must be unique within one request, and this identifier must also be used in the corresponding pre-award catalogue, if the element sent.

See further details and examples of the response in a pre-award catalogue in chapter <<additional-prop>>

.Example to request a specific proportion of fat in milk
[source, xml, indent=0]
----
include::../../{snippet-dir}/CatalogueRequest-guide.xml[tags=Request-of-fat-in-milk]
----
<1> Unique (in this request) identifier
<2> the name of the requested property as free text
<3> The quantity and unit code requested, here 3%
<4> No relevance code is sent, hence it is mandatory to send this information in the corresponding pre-award catalogue

.Example to request a specific range of item net quantity
[source, xml, indent=0]
----
include::../../{snippet-dir}/CatalogueRequest-guide.xml[tags=Request-of-specific-range]
----
<1> the name of the requested property as free text
<2> Minimum requested item net quantity
<3> Maximum requested item net quantity
<4> The relevance code, according to {relevance}

.Example to request a specific element
[source, xml, indent=0]
----
include::../../{snippet-dir}/CatalogueRequest-guide.xml[tags=Request-element]
----
<1> Unique (in this request) identifier
<2> Business term identifier of the requested element
<3> the name of the requested element as found in the code list
