= Quantities and Units

There are various quantities and units that can be used in the Pre-award catalogue. Here is a detailed list of relevant quantities and units:

****
Orderable unit (OrderableUnit)::
The unit in which the item described in this catalogue line can be ordered.

Item net quantity (ContentUnitQuantity)::
The net quantity of the item that is contained in each consumable unit (excluding packaging material), e.g. ml in bottles of shampoo.

Order quantity increment (OrderQuantityIncrementNumeric)::
Possible limitation to the number of articles that can be ordered. If the Quantity increment is 6 the article shall be ordered in a quantity of 6, 12, 18 etc.

Minimum order quantity (MinimumOrderQuantity)::
The smallest number of items that can be ordered (most often 1).

Maximum order quantity (MaximumOrderQuantity)::
The largest number of items that can be ordered (most often unlimited).

Packed quantity (Item/PackQuantity)::
Number of items on next lower level, e.g. number of Consumer units in a Trading unit.

Consumable unit quantity (Item/PackSizeNumeric)::
Number of Consumer items in the orderable unit. E.g. number of bottles on a pallet.

Item quantity for component related item(ComponentRelatedItem/Quantity)::
Quantity of the related component.

Handling unit height or length or width or gross weight (Dimension/Measure)::
The dimensions of the handling unit.

Handling unit minimum storage temperature (Dimension/MinimumMeasure)::
The lower margin of the recommended storage temperature range for the item.

Handling unit maximum storage temperature (Dimension/MaximumMeasure)::
The upper margin of the recommended storage temperature range for the item.

Handling unit minimum storage humidity (Dimension/MinimumMeasure)::
The lower margin of the recommended storage humidity range for the item.

Handling unit maximum storage humidity (Dimension/MaximumMeasure)::
The upper margin of the recommended storage humidity range for the item.

Item property value quantity (AdditionalItemProperty/ValueQuantity)::
The quantity of the requested item property.

****

.Example of quantites and units.

[cols="5h,2,2,2,2", options="header"]
|===
|Description |Element (from CatalogueLine level) |1 bottle | Case of 6 bottles | Pallet of 18 cases
|*Line identifier*| ID| 1| 2| 3
|*Sellers item identifier* | SellersItemIdentification/ID | 2222| 222| 22
|*Item name* | Item/Name |Milk 1L|6 x 1L Milk| Milk
|*Orderable Unit* | OrderableUnit| EA| CS| PF
|*Packaging level* | PackLevelCode|CU |TU| DU
|*Packed quantity* |Item/PackQuantity|  |6 |18
|*Packed quantity unit* |Item/PackQuantity/@unitCode| |EA |CS
|*Consumable unit quantity*|Item/PackSizeNumeric |1 |6 |180
|*Item net quantity* |ContentUnitQuantity |250|1500|30000
|*Item net quantity unit*|ContentUnitQuantity/@unitCode|MLT|MLT|MLT
|*Minimum order quantity*|MinimumOrderQuantity|1 | 1| 1
|*Minimum order quantity unit*|MinimumOrderQuantity/@unitCode|EA |CS | PF
|*Component related item identifier*|ComponentRelatedItem/ID| |2222 | 222
|*Item quantity for component related item*|ComponentRelatedItem/Quantity| |10 |18

|===

[source]
.Example of catalogue line with line identifier = 1 from the above table.
----
<cac:CatalogueLine>
  <cbc:ID>1</cbc:ID>
  <cbc:OrderableUnit>EA</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="MLT">250</cbc:ContentUnitQuantity>
  <cbc:OrderQuantityIncrementNumeric>1</cbc:OrderQuantityIncrementNumeric>
  <cbc:MinimumOrderQuantity unitCode="EA">1</cbc:MinimumOrderQuantity>
  <cbc:PackLevelCode>CU</cbc:PackLevelCode>
  ...
  <cac:Item>
    <cbc:Name languageID="en">Milk 1 Liter</cbc:Name>
    <cbc:PackSizeNumeric>1</cbc:PackSizeNumeric>
    <cac:SellersItemIdentification>
      <cbc:ID>2222</cbc:ID>
    </cac:SellersItemIdentification>
  ...
  </cac:Item>
  ...
</cac:CatalogueLine>
----
