= Validity Period

In the catalogue request the contracting authority can state the requested delivery period for an item by using the element 'cac:LineValidityPeriod'. If several options exist for the requested delivery period of a particular item/service, the contracting authority can state which is the preferred period (only one instance allowed), and what is the alternative period(s).

.Example of the requested delivery period in the pre-award catalogue request
[source, xml, indent=0]
----
include::../../{snippet-dir}/CatalogueRequest-guide.xml[tags=ValidityPeriod;ValidityPeriod2]
----
<1> Code 69 indicating the preferred delivery period
<2> Code 120 indicating an alternative delivery period

WARNING: Only one instance of Line validity period with Validity description code = '69' is allowed for the same item/service


In the Pre-Award Catalogue the following validity periods can be stated:

* Validity period on document level (mandatory), used to state the validity period for the entire Pre-Award Catalogue.
* Validity period for a catalogue line
* Validity period for price (See also section 4.7)

WARNING: All validity periods shall have both start date and end date, and the start date shall be earlier than the end date


Example of validity periods in a Pre-Award Catalogue:

.Document level (mandatory)
[source, xml, indent=0]
----
include::../../{snippet-dir}/Catalogue-guide.xml[tags=ValidityPeriod]
----

.Catalogue line
[source, xml, indent=0]
----
include::../../{snippet-dir}/Catalogue-guide.xml[tags=LineValidityPeriod]
----

.Two different validity period for a given price
[source, xml, indent=0]
----
include::../../{snippet-dir}/Catalogue-guide.xml[tags=Diff-LineValidityPeriod]
----
